### ISSUE TITLE
About the "INFO max_node XXX" command

### ISSUE THREAD

**Issue by wind23** [Hexik/Embryo_engine#2]
I know that the command `INFO max_node XXX` is not an original Gomocup protocol, and it is provided by the Yixin Board.

I tried it with the engine of Embryo, and found that it is supported by Embryo.

However, I found a small problem while using this command with Embryo. The maximum number of node limit supported by Embryo is `2147M`, and the engine will stop after that. Does there exist any way to set a larger node limit? Thanks!

**Comment by Hexik** [comment]
Generic input parser uses int32 so the limitation to the 2147M.

I will switch the parser to the int64.
